=== AliaksandrKlimets/Task1.0/src/coffe.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:tns="http://tempuri.org/PurchaseOrderSchema.xsd"
        targetNamespace="http://tempuri.org/PurchaseOrderSchema.xsd"
        elementFormDefault="qualified">
    <element name="coffeeElements">
        <complexType>
            <sequence>
                <element name="coffee"
                         type="tns:Coffee"
                         minOccurs="0"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Coffee">
        <sequence>
            <element name="physicalState">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Corn"/>
                        <enumeration value="Ground"/>
                        <enumeration value="Soluble in cans"/>
                        <enumeration value="Soluble in packets"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="kind">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Arabic"/>
                        <enumeration value="Liberic"/>
                        <enumeration value="Robust"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="amount" type="double"/>
            <element name="packAmount" type="double"/>
            <element name="cost" type="double"/>
            <element name="weight" type="double"/>
        </sequence>
    </complexType>
</schema>

=== AliaksandrKlimets/Task1.0/src/cofee.xml
<?xml version="1.0" encoding="UTF-8" ?>
<coffeeElements xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns="http://tempuri.org/PurchaseOrderSchema.xsd"
                xsi:noNamespaceSchemaLocation="coffe.xsd">
    <coffee>
        <physicalState>Corn</physicalState>
        <kind>Liberic</kind>
        <amount>10</amount>
        <packAmount>20</packAmount>
        <cost>30</cost>
        <weight>40</weight>
    </coffee>
    <coffee>
        <physicalState>Ground</physicalState>
        <kind>Arabic</kind>
        <amount>20</amount>
        <packAmount>30</packAmount>
        <cost>10</cost>
        <weight>40</weight>
    </coffee>
    <coffee>
        <physicalState>Soluble in cans</physicalState>
        <kind>Arabic</kind>
        <amount>10</amount>
        <packAmount>10</packAmount>
        <cost>20</cost>
        <weight>40</weight>
    </coffee>
    <coffee>
        <physicalState>Corn</physicalState>
        <kind>Robust</kind>
        <amount>10</amount>
        <packAmount>20</packAmount>
        <cost>10</cost>
        <weight>10</weight>
    </coffee>
    <coffee>
        <physicalState>Ground</physicalState>
        <kind>Robust</kind>
        <amount>50</amount>
        <packAmount>10</packAmount>
        <cost>20</cost>
        <weight>10</weight>
    </coffee>
</coffeeElements>
